services:
  web:
    build: 
      context: ./apps/web
      dockerfile: Dockerfile
    expose:
      - "5173"
    depends_on:
      - api
    networks:
      - eval-net
    environment:
      - VITE_API_BASE_URL=/api
    volumes:
      - ./apps/web/src:/app/src
      - ./apps/web/public:/app/public
      - ./apps/web/index.html:/app/index.html
      - ./apps/web/vite.config.js:/app/vite.config.js

  api:
    build:
      context: .
      dockerfile: apps/server/Dockerfile
    volumes:
      - ./libs/OpenCompass:/app/libs/OpenCompass
      - ./workspace:/app/workspace
    command: uvicorn apps.server.src.main:app --host 0.0.0.0 --port 8000
    ports:
      - "8000:8000"
    depends_on:
      - redis
      - mysql
    networks:
      - eval-net
    env_file:
      - .env

  celery_worker:
    build:
      context: .
      dockerfile: apps/server/Dockerfile
    volumes:
      - ./libs/OpenCompass:/app/libs/OpenCompass
      - ./workspace:/app/workspace
    command: celery -A celery_app:celery_app worker --loglevel=INFO --concurrency=1 -Q eval_tasks
    depends_on:
      - redis
      - mysql
    networks:
      - eval-net

  redis:
    image: redis:alpine
    ports:
      - "6379:6379"
    volumes:
      - redis_data:/data
    networks:
      - eval-net

  mysql:
    image: mysql:8.0
    ports:
      - "3306:3306"
    environment:
      MYSQL_ROOT_PASSWORD: ${MYSQL_ROOT_PASSWORD}
      MYSQL_DATABASE: ${MYSQL_DB}
      MYSQL_USER: ${MYSQL_USER}
      MYSQL_PASSWORD: ${MYSQL_PASSWORD}
    volumes:
      - ./workspace/mysql_data:/var/lib/mysql
      - ./docker/mysql/my.cnf:/etc/mysql/conf.d/my.cnf
    networks:
      - eval-net
    healthcheck:
      test: ["CMD", "mysqladmin", "ping", "-h", "localhost"]
      interval: 5s
      timeout: 10s
      retries: 5
  nginx:
      image: nginx:alpine
      ports:
        - "80:80"
      volumes:
        - ./docker/nginx/dev.conf:/etc/nginx/conf.d/default.conf
      depends_on:
        - web
        - api
      networks:
        - eval-net
volumes:
  redis_data:
  
networks:
  eval-net:
    driver: bridge 