services:
  web:
    build:
      context: ..
      dockerfile: docker/web/Dockerfile
      args:
        - DOCKER_ENV=true
    expose:
      - "5173:5173"
    depends_on:
      - api
    networks:
      - eval-net
    environment:
      - VITE_API_BASE_URL=/api
      - REDIS_URL=redis://redis:6379/0
      - TZ=Asia/Shanghai
    volumes:
      - ../apps/web/src:/app/src
      - ../apps/web/public:/app/public
      - ../apps/web/index.html:/app/index.html
      - ../apps/web/vite.config.js:/app/vite.config.js

  api:
    build:
      context: ..
      dockerfile: docker/api/Dockerfile
    volumes:
      - ../workspace:/app/workspace
    command: uvicorn apps.server.src.main:app --host 0.0.0.0 --port 8000
    ports:
      - "8000:8000"
    environment:
      - MYSQL_HOST=mysql
      - REDIS_URL=redis://redis:6379/0
      - CELERY_BROKER_URL=redis://redis:6379/0
      - CELERY_RESULT_BACKEND=redis://redis:6379/1
      - DIFY2OPENAI_URL=http://dify2openai:3099/v1/
      - TZ=Asia/Shanghai
      - PYTHONUNBUFFERED=1
    depends_on:
      - redis
      - mysql
    networks:
      - eval-net
    env_file:
      - .env
    tty: true
    stdin_open: true

  celery_worker:
    build:
      context: ..
      dockerfile: docker/celery_worker/Dockerfile
    volumes:
      - ../workspace:/app/workspace
    command: celery -A celery_app:celery_app worker --loglevel=INFO --concurrency=1 -Q eval_tasks
    environment:
      - MYSQL_HOST=mysql
      - REDIS_URL=redis://redis:6379/0
      - CELERY_BROKER_URL=redis://redis:6379/0
      - CELERY_RESULT_BACKEND=redis://redis:6379/1
      - DIFY2OPENAI_URL=http://dify2openai:3099/v1/
      - TZ=Asia/Shanghai
      - PYTHONUNBUFFERED=1
    depends_on:
      - redis
      - mysql
      - dify2openai
    networks:
      - eval-net
    env_file:
      - .env
    tty: true
    stdin_open: true

  redis:
    image: redis:alpine
    ports:
      - "6379:6379"
    volumes:
      - redis_data:/data
    networks:
      - eval-net
    environment:
      - TZ=Asia/Shanghai

  mysql:
    image: mysql:8.0
    ports:
      - "3306:3306"
    environment:
      MYSQL_ROOT_PASSWORD: ${MYSQL_ROOT_PASSWORD}
      MYSQL_DATABASE: ${MYSQL_DB}
      MYSQL_USER: ${MYSQL_USER}
      MYSQL_PASSWORD: ${MYSQL_PASSWORD}
      TZ: Asia/Shanghai
    volumes:
      - ../workspace/mysql_data:/var/lib/mysql
      - ../docker/mysql/my.cnf:/etc/mysql/conf.d/my.cnf
      - ../initdb:/docker-entrypoint-initdb.d
    networks:
      - eval-net
    healthcheck:
      test: ["CMD", "mysqladmin", "ping", "-h", "localhost"]
      interval: 5s
      timeout: 10s
      retries: 10

  dify2openai:
    image: node:18.20.2-bullseye
    working_dir: /app
    volumes:
      - ../libs/dify2openai:/app
    ports:
      - "3099:3099"
    networks:
      - eval-net
    command: >
      sh -c "npm install &&
             npm run start"
    environment:
      NODE_ENV: production
      TZ: Asia/Shanghai

  nginx:
    image: nginx:alpine
    ports:
      - "80:80"
    volumes:
      - ../docker/nginx/dev.conf:/etc/nginx/conf.d/default.conf
    depends_on:
      - web
      - api
    networks:
      - eval-net
    environment:
      - TZ=Asia/Shanghai

volumes:
  redis_data:

networks:
  eval-net:
    driver: bridge 